my_site/my_app/urls.py
from django.urls import path
from .views import thank_you, review_form, list, delete, home

app_name = 'my_app'

urlpatterns = [
    path('thank_you/', thank_you, name='thank_you'),
    path('review/', review_form, name='review_form'),
    path('list/', list, name='list'),
    path('delete/', delete, name='delete'),
    path('', home, name='home'),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls'))
]

my_site/my_app/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    stars = models.IntegerField()
    review = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.review}   [[[[{self.stars}]]]]"

my_site/my_app/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm, Textarea

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = '__all__'
        widgets = {
            'review' : Textarea(),
        }

my_site/my_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ReviewForm
from .models import Review

# Create your views here
def thank_you(request):
    return render(request, 'my_app/thank_you.html')

def review_form(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('my_app:thank_you'))
    else:
        form = ReviewForm()
        return render(request, 'my_app/form.html', context={'form':form})    
    
def list(request):
    all_review = Review.objects.all()
    context = {'all_review':all_review}
    return render(request, 'my_app/list.html', context=context)

def delete(request):
    if request.POST:
        first_name = request.POST['first_name']
        try:
            Review.objects.get(first_name=str(first_name)).delete()
            return redirect(reverse('my_app:list'))
        except:
            print('Name is not Found')
            return redirect(reverse('my_app:list'))
    else:
        return render(request, 'my_app/delete.html')
    
def home(request):
    return render(request, 'my_app/home.html')


my_site/my_app/templates/my_app/delete.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}    
    <h1>Delete</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="first_name">Enter Name to delete the entry.</label>
        <div class="form-group">
            <input class="form-control" type="text", id="first_name" name="first_name" >
                <p></p>
        </div>
        <div>
            <input class="btn btn-primary" type="submit">
        </div>
    </form>
    {% endblock %}
</body>
</html>

my_site/my_app/templates/my_app/form.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}        
    {% load crispy_forms_filters %}
    {% load crispy_forms_tags %}
    <h1>Review Form</h1>
    <div class="mb3">
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary" type="submit">
        </form>
    </div>
    {% endblock %}
</body>
</html>

my_site/my_app/templates/my_app/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>Home Page</h1>
    {% endblock %}
</body>
</html>

my_site/my_app/templates/my_app/list.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>List</h1>
    <div class="mb3">
        <ul>
            {% for i in all_review %}
            <li>
                <h5>{{i.first_name|lower|capfirst}} {{i.last_name|lower|capfirst}}</h5>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endblock %}
</body>
</html>

my_site/my_app/templates/my_app/thank_you.html
{% extends 'base.html' %}
{% block content %}

<h1>Thank You</h1>
{% endblock %}

my_site/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'my_app:home' %}">Home Page</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'my_app:list' %}">List</a>
              <a class="nav-link" href="{% url 'my_app:review_form' %}">Review Form</a>
              <a class="nav-link" href="{% url 'my_app:delete' %}">Delete</a>
              <a class="nav-link" href="{% url 'my_app:thank_you' %}">Thank You</a>
            </div>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
</body>
</html>